# https://github.com/LittleToonCat/OtpGo/blob/main/clientagent/messages.go

CLIENT_LOGIN       = 1
CLIENT_LOGIN_RESP  = 2
CLIENT_GET_AVATARS = 3

CLIENT_GO_GET_LOST             = 4
CLIENT_GET_AVATARS_RESP        = 5
CLIENT_CREATE_AVATAR           = 6
CLIENT_CREATE_AVATAR_RESP      = 7
CLIENT_GET_FRIEND_LIST         = 10
CLIENT_GET_FRIEND_LIST_RESP    = 11
CLIENT_GET_AVATAR_DETAILS      = 14
CLIENT_GET_AVATAR_DETAILS_RESP = 15
CLIENT_LOGIN_2                 = 16
CLIENT_LOGIN_2_RESP            = 17

CLIENT_OBJECT_UPDATE_FIELD                     = 24
CLIENT_OBJECT_UPDATE_FIELD_RESP                = 24
CLIENT_OBJECT_DISABLE                          = 25
CLIENT_OBJECT_DISABLE_RESP                     = 25
CLIENT_OBJECT_DISABLE_OWNER                    = 26
CLIENT_OBJECT_DISABLE_OWNER_RESP               = 26
CLIENT_OBJECT_DELETE                           = 27
CLIENT_OBJECT_DELETE_RESP                      = 27
CLIENT_SET_ZONE_CMU                            = 29
CLIENT_REMOVE_ZONE                             = 30
CLIENT_SET_AVATAR                              = 32
CLIENT_CREATE_OBJECT_REQUIRED                  = 34
CLIENT_CREATE_OBJECT_REQUIRED_RESP             = 34
CLIENT_CREATE_OBJECT_REQUIRED_OTHER            = 35
CLIENT_CREATE_OBJECT_REQUIRED_OTHER_RESP       = 35
CLIENT_CREATE_OBJECT_REQUIRED_OTHER_OWNER      = 36
CLIENT_CREATE_OBJECT_REQUIRED_OTHER_OWNER_RESP = 36

CLIENT_REQUEST_GENERATES = 36

CLIENT_DISCONNECT = 37

CLIENT_GET_STATE_RESP     = 47
CLIENT_DONE_INTEREST_RESP = 48

CLIENT_DELETE_AVATAR = 49

CLIENT_DELETE_AVATAR_RESP = 5

CLIENT_HEARTBEAT      = 52
CLIENT_FRIEND_ONLINE  = 53
CLIENT_FRIEND_OFFLINE = 54
CLIENT_REMOVE_FRIEND  = 56

CLIENT_CHANGE_PASSWORD = 65

CLIENT_SET_NAME_PATTERN        = 67
CLIENT_SET_NAME_PATTERN_ANSWER = 68

CLIENT_SET_WISHNAME       = 70
CLIENT_SET_WISHNAME_RESP  = 71
CLIENT_SET_WISHNAME_CLEAR = 72
CLIENT_SET_SECURITY       = 73

CLIENT_SET_DOID_RANGE = 74

CLIENT_GET_AVATARS_RESP2 = 75
CLIENT_CREATE_AVATAR2    = 76
CLIENT_SYSTEM_MESSAGE    = 78
CLIENT_SET_AVTYPE        = 80

CLIENT_GET_PET_DETAILS      = 81
CLIENT_GET_PET_DETAILS_RESP = 82

CLIENT_ADD_INTEREST    = 97
CLIENT_REMOVE_INTEREST = 99
CLIENT_OBJECT_LOCATION = 102

CLIENT_LOGIN_3      = 111
CLIENT_LOGIN_3_RESP = 110

CLIENT_GET_FRIEND_LIST_EXTENDED      = 115
CLIENT_GET_FRIEND_LIST_EXTENDED_RESP = 116

CLIENT_SET_FIELD_SENDABLE = 120

CLIENT_SYSTEMMESSAGE_AKNOWLEDGE = 123
CLIENT_CHANGE_GENERATE_ORDER    = 124

# new toontown specific login message, adds last logged in, and if child account has parent acount
CLIENT_LOGIN_TOONTOWN      = 125
CLIENT_LOGIN_TOONTOWN_RESP = 126

CLIENT_DISCONNECT_GENERIC                = 1
CLIENT_DISCONNECT_RELOGIN                = 100
CLIENT_DISCONNECT_OVERSIZED_DATAGRAM     = 106
CLIENT_DISCONNECT_NO_HELLO               = 107
CLIENT_DISCONNECT_CHAT_AUTH_ERROR        = 120
CLIENT_DISCONNECT_ACCOUNT_ERROR          = 122
CLIENT_DISCONNECT_NO_HEARTBEAT           = 345
CLIENT_DISCONNECT_INVALID_MSGTYPE        = 108
CLIENT_DISCONNECT_TRUNCATED_DATAGRAM     = 109
CLIENT_DISCONNECT_ANONYMOUS_VIOLATION    = 113
CLIENT_DISCONNECT_FORBIDDEN_INTEREST     = 115
CLIENT_DISCONNECT_MISSING_OBJECT         = 117
CLIENT_DISCONNECT_FORBIDDEN_FIELD        = 118
CLIENT_DISCONNECT_FORBIDDEN_RELOCATE     = 119
CLIENT_DISCONNECT_BAD_VERSION            = 125
CLIENT_DISCONNECT_FIELD_CONSTRAINT       = 127
CLIENT_DISCONNECT_SESSION_OBJECT_DELETED = 153

# Internal message types
# https://github.com/LittleToonCat/OtpGo/blob/main/util/msgtypes.go

ZONE_BITS                         = 32
STATESERVER_CONTEXT_WAKE_CHILDREN = 1001

# Control range
CONTROL_MSGTYPE_MIN      = 2000
CONTROL_MSGTYPE_MAX      = 2999
# ClientAgent range
CLIENT_AGENT_MSGTYPE_MIN = 3000
CLIENT_AGENT_MSGTYPE_MAX = 3999
# StateServer range
STATESERVER_MSGTYPE_MIN  = 2000
STATESERVER_MSGTYPE_MAX  = 2999
# DatabaseServer range
DBSERVER_MSGTYPE_MIN     = 1000
DBSERVER_MSGTYPE_MAX     = 1999

# Reserved
RESERVED_MSG_TYPE = 0

# Control messages
INVALID_CHANNEL            = 0
CHANNEL_CLIENT_BROADCAST   = 4014  # From AIMsgTypes.py
BCHAN_STATESERVERS         = 12
BCHAN_DBSERVERS            = 13
PARENT_PREFIX              = 1 << ZONE_BITS
DATABASE_PREFIX            = 2 << ZONE_BITS
CONTROL_MESSAGE            = 4001
CONTROL_SET_CHANNEL        = 2001
CONTROL_REMOVE_CHANNEL     = 2002
CONTROL_SET_CON_NAME       = 2004
CONTROL_SET_CON_URL        = 2005
CONTROL_ADD_RANGE          = 2008
CONTROL_REMOVE_RANGE       = 2009
CONTROL_ADD_POST_REMOVE    = 2010
CONTROL_CLEAR_POST_REMOVES = 2011
CONTROL_LOG_MESSAGE        = 2012

# ClientAgent messages
CLIENT_AGENT_SET_STATE                = 3000
CLIENT_AGENT_SET_CLIENT_ID            = 3001
CLIENT_AGENT_SEND_DATAGRAM            = 3002
CLIENT_AGENT_EJECT                    = 3004
CLIENT_AGENT_DROP                     = 3005
CLIENT_AGENT_GET_NETWORK_ADDRESS      = 3006
CLIENT_AGENT_GET_NETWORK_ADDRESS_RESP = 3007
CLIENT_AGENT_DECLARE_OBJECT           = 3010
CLIENT_AGENT_UNDECLARE_OBJECT         = 3011
CLIENT_AGENT_ADD_SESSION_OBJECT       = 3012
CLIENT_AGENT_REMOVE_SESSION_OBJECT    = 3013
CLIENT_AGENT_GET_TLVS                 = 3014
CLIENT_AGENT_GET_TLVS_RESP            = 3015
CLIENT_AGENT_OPEN_CHANNEL             = 3100
CLIENT_AGENT_CLOSE_CHANNEL            = 3105
CLIENT_AGENT_ADD_POST_REMOVE          = 3110
CLIENT_AGENT_CLEAR_POST_REMOVES       = 3111
CLIENT_AGENT_SET_INTEREST             = 3106
CLIENT_AGENT_REMOVE_INTEREST          = 3107

# StateServer control and object messages
STATESERVER_OBJECT_GENERATE_WITH_REQUIRED       = 2001
STATESERVER_OBJECT_GENERATE_WITH_REQUIRED_OTHER = 2003
STATESERVER_OBJECT_UPDATE_FIELD                 = 2004
STATESERVER_OBJECT_UPDATE_FIELD_MULTIPLE        = 2005
STATESERVER_OBJECT_DELETE_RAM                   = 2007
STATESERVER_OBJECT_SET_ZONE                     = 2008
STATESERVER_OBJECT_CHANGE_ZONE                  = 2009
STATESERVER_OBJECT_NOTFOUND                     = 2015
STATESERVER_OBJECT_QUERY_FIELD                  = 2024
STATESERVER_OBJECT_QUERY_FIELD_RESP             = 2062
STATESERVER_OBJECT_QUERY_FIELDS                 = 2080
STATESERVER_OBJECT_QUERY_FIELDS_RESP            = 2081
STATESERVER_QUERY_OBJECT_ALL                    = 2020
STATESERVER_QUERY_OBJECT_ALL_RESP               = 2030
STATESERVER_OBJECT_DELETE_FIELD_RAM             = 2031
STATESERVER_OBJECT_DELETE_FIELDS_RAM            = 2032
# StateServer visibility messages
STATESERVER_OBJECT_ENTER_LOCATION_WITH_REQUIRED       = 2042
STATESERVER_OBJECT_ENTER_LOCATION_WITH_REQUIRED_OTHER = 2043
STATESERVER_OBJECT_LOCATE                             = 2022
STATESERVER_OBJECT_LOCATE_RESP                        = 2023
STATESERVER_ADD_AI_RECV                               = 2045
STATESERVER_OBJECT_LOCATION_ACK                       = 2046
STATESERVER_OBJECT_LEAVING_AI_INTEREST                = 2033
STATESERVER_OBJECT_ENTER_AI_RECV                      = 2067
STATESERVER_OBJECT_GET_AI                             = 2054
STATESERVER_OBJECT_GET_AI_RESP                        = 2055
STATESERVER_SHARD_REST                                = 2061
STATESERVER_OBJECT_ENTER_INTEREST_WITH_REQUIRED       = 2071
STATESERVER_OBJECT_ENTER_INTEREST_WITH_REQUIRED_OTHER = 2072
STATESERVER_OBJECT_ENTER_OWNER_RECV                   = 2068
STATESERVER_OBJECT_CHANGE_OWNER_RECV                  = 2069
STATESERVER_OBJECT_SET_OWNER_RECV                     = 2070
STATESERVER_OBJECT_SET_OWNER_RECV_WITH_ALL            = 2075
STATESERVER_OBJECT_GET_OWNER                          = 2064
STATESERVER_OBJECT_GET_OWNER_RESP                     = 2065
# StateServer parent-method messages
STATESERVER_OBJECT_GET_ZONE_OBJECTS     = 2100
STATESERVER_OBJECT_GET_ZONES_OBJECTS    = 2102
STATESERVER_OBJECT_GET_CHILDREN         = 2104
STATESERVER_OBJECT_GET_ZONE_COUNT       = 2110
STATESERVER_OBJECT_GET_ZONE_COUNT_RESP  = 2111
STATESERVER_OBJECT_GET_ZONES_COUNT      = 2112
STATESERVER_OBJECT_GET_ZONES_COUNT_RESP = 2113
STATESERVER_OBJECT_GET_CHILD_COUNT      = 2114
STATESERVER_OBJECT_GET_CHILD_COUNT_RESP = 2115
STATESERVER_OBJECT_DELETE_ZONE          = 2120
STATESERVER_OBJECT_DELETE_ZONES         = 2122
STATESERVER_OBJECT_DELETE_CHILDREN      = 2124
STATESERVER_GET_ACTIVE_ZONES            = 2125
STATESERVER_GET_ACTIVE_ZONES_RESP       = 2126
# DBSS object messages
STATESERVER_OBJECT_CREATE_WITH_REQUIRED_CONTEXT     = 2050
STATESERVER_OBJECT_CREATE_WITH_REQUIR_OTHER_CONTEXT = 2051
DBSS_OBJECT_GET_ACTIVATED                           = 2207
DBSS_OBJECT_GET_ACTIVATED_RESP                      = 2208
DBSS_OBJECT_DELETE_FIELD_RAM                        = 2230
DBSS_OBJECT_DELETE_FIELDS_RAM                       = 2231
DBSS_OBJECT_DELETE_DISK                             = 2232

# DatabaseServer messages
DBSERVER_CREATE_STORED_OBJECT      = 1003
DBSERVER_CREATE_STORED_OBJECT_RESP = 1004
DBSERVER_DELETE_STORED_OBJECT      = 1008
DBSERVER_GET_STORED_VALUES         = 1012
DBSERVER_GET_STORED_VALUES_RESP    = 1013
DBSERVER_SET_STORED_VALUES         = 1014
